OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 3

DATASET:
  NAME: 'virat'
  ROOT: '/home/berko/Data'
  VALIDATION_SET: 'val'
  TRAIN_SET: 'train'
  NUM_CLASSES: 3
  IMAGE_SIZE:
  - 360
  - 640
MODEL:
  BACKBONE: 'MobilenetV2'
  PRETRAINED: 'imagenet'
TRAIN:
  AUGMENT: true
  NUM_EPOCHS: 20
  RESUME: true
  OPTIMIZER: 'adam'
  LR: 0.001
  WD: 0.0005
  MOMENTUM: 0.9
  IMAGE_SIZE:
    - 360
    - 640
  NESTEROV: false
  BATCH_SIZE: 16
  CLASS_WEIGHTS:
    - 1
    - 100
    - 100
  BEST_SAVE_PATH: 'virat_mobilenetv2.keras'
